#include "Dx12Screen.h"
#include <d3d12sdklayers.h>
#include <cstdio>
#include <cstring>
template<class T>using Com=Microsoft::WRL::ComPtr<T>;
static void H(HRESULT hr){if(FAILED(hr)){printf("failed %08lx\n",hr);ExitProcess(1);}}
int main(){
 if(HeadsetColorFormat(DXGI_FORMAT_R8G8B8A8_UNORM)!=DXGI_FORMAT_R8G8B8A8_UNORM_SRGB||HeadsetColorFormat(DXGI_FORMAT_B8G8R8A8_UNORM)!=DXGI_FORMAT_B8G8R8A8_UNORM_SRGB||HeadsetColorFormat(DXGI_FORMAT_R16G16B16A16_FLOAT)!=DXGI_FORMAT_R16G16B16A16_FLOAT)return 2;
 Com<ID3D12Debug> debug;if(SUCCEEDED(D3D12GetDebugInterface(IID_PPV_ARGS(&debug))))debug->EnableDebugLayer();Com<IDXGIFactory4> factory;H(CreateDXGIFactory1(IID_PPV_ARGS(&factory)));Com<IDXGIAdapter> adapter;H(factory->EnumWarpAdapter(IID_PPV_ARGS(&adapter)));Com<ID3D12Device> device;H(D3D12CreateDevice(adapter.Get(),D3D_FEATURE_LEVEL_11_0,IID_PPV_ARGS(&device)));
 Com<ID3D12CommandQueue> queue;D3D12_COMMAND_QUEUE_DESC q{};H(device->CreateCommandQueue(&q,IID_PPV_ARGS(&queue)));Com<ID3D12CommandAllocator> allocator;H(device->CreateCommandAllocator(D3D12_COMMAND_LIST_TYPE_DIRECT,IID_PPV_ARGS(&allocator)));Com<ID3D12GraphicsCommandList> list;H(device->CreateCommandList(0,D3D12_COMMAND_LIST_TYPE_DIRECT,allocator.Get(),nullptr,IID_PPV_ARGS(&list)));
 auto barrier=[&](ID3D12Resource* r,D3D12_RESOURCE_STATES a,D3D12_RESOURCE_STATES b){D3D12_RESOURCE_BARRIER x{};x.Type=D3D12_RESOURCE_BARRIER_TYPE_TRANSITION;x.Transition={r,~0u,a,b};list->ResourceBarrier(1,&x);};
 D3D12_RESOURCE_DESC d{};d.Dimension=D3D12_RESOURCE_DIMENSION_TEXTURE2D;d.Width=d.Height=4;d.MipLevels=d.DepthOrArraySize=d.SampleDesc.Count=1;d.Format=DXGI_FORMAT_R8G8B8A8_UNORM;d.Flags=D3D12_RESOURCE_FLAG_ALLOW_RENDER_TARGET;D3D12_HEAP_PROPERTIES hp{};hp.Type=D3D12_HEAP_TYPE_DEFAULT;Com<ID3D12Resource> source,dest;H(device->CreateCommittedResource(&hp,D3D12_HEAP_FLAG_NONE,&d,D3D12_RESOURCE_STATE_RENDER_TARGET,nullptr,IID_PPV_ARGS(&source)));d.Format=HeadsetColorFormat(d.Format);H(device->CreateCommittedResource(&hp,D3D12_HEAP_FLAG_NONE,&d,D3D12_RESOURCE_STATE_COPY_DEST,nullptr,IID_PPV_ARGS(&dest)));
 Com<ID3D12DescriptorHeap> heap;D3D12_DESCRIPTOR_HEAP_DESC hd{};hd.Type=D3D12_DESCRIPTOR_HEAP_TYPE_RTV;hd.NumDescriptors=1;H(device->CreateDescriptorHeap(&hd,IID_PPV_ARGS(&heap)));auto h=heap->GetCPUDescriptorHandleForHeapStart();device->CreateRenderTargetView(source.Get(),nullptr,h);float color[]={0.5f,0.25f,0.75f,1};list->ClearRenderTargetView(h,color,0,nullptr);barrier(source.Get(),D3D12_RESOURCE_STATE_RENDER_TARGET,D3D12_RESOURCE_STATE_COPY_SOURCE);list->CopyResource(dest.Get(),source.Get());barrier(dest.Get(),D3D12_RESOURCE_STATE_COPY_DEST,D3D12_RESOURCE_STATE_COPY_SOURCE);
 D3D12_RESOURCE_DESC b{};b.Dimension=D3D12_RESOURCE_DIMENSION_BUFFER;b.Width=1024;b.Height=b.MipLevels=b.DepthOrArraySize=b.SampleDesc.Count=1;b.Layout=D3D12_TEXTURE_LAYOUT_ROW_MAJOR;hp.Type=D3D12_HEAP_TYPE_READBACK;Com<ID3D12Resource> read;H(device->CreateCommittedResource(&hp,D3D12_HEAP_FLAG_NONE,&b,D3D12_RESOURCE_STATE_COPY_DEST,nullptr,IID_PPV_ARGS(&read)));D3D12_TEXTURE_COPY_LOCATION a{},z{};a.pResource=read.Get();a.Type=D3D12_TEXTURE_COPY_TYPE_PLACED_FOOTPRINT;a.PlacedFootprint.Footprint={d.Format,4,4,1,256};z.pResource=dest.Get();z.Type=D3D12_TEXTURE_COPY_TYPE_SUBRESOURCE_INDEX;list->CopyTextureRegion(&a,0,0,0,&z,nullptr);H(list->Close());ID3D12CommandList* lists[]={list.Get()};queue->ExecuteCommandLists(1,lists);Com<ID3D12Fence> fence;H(device->CreateFence(0,D3D12_FENCE_FLAG_NONE,IID_PPV_ARGS(&fence)));H(queue->Signal(fence.Get(),1));auto event=CreateEventW(nullptr,FALSE,FALSE,nullptr);H(fence->SetEventOnCompletion(1,event));if(WaitForSingleObject(event,5000)!=WAIT_OBJECT_0)return 3;unsigned char* data{};H(read->Map(0,nullptr,reinterpret_cast<void**>(&data)));for(unsigned y=0;y<4;++y)for(unsigned x=0;x<4;++x){auto p=data+y*256+x*4;if(p[0]!=128||p[1]!=64||p[2]!=191||p[3]!=255)return 4;}read->Unmap(0,nullptr);
 Com<ID3D12InfoQueue> info;if(SUCCEEDED(device.As(&info)))for(UINT64 i=0;i<info->GetNumStoredMessages();++i){SIZE_T n{};info->GetMessage(i,nullptr,&n);std::vector<char> bytes(n);auto m=reinterpret_cast<D3D12_MESSAGE*>(bytes.data());info->GetMessage(i,m,&n);if(m->Severity<=D3D12_MESSAGE_SEVERITY_ERROR){puts(m->pDescription);return 5;}}
 puts("PASS UNORM to sRGB GPU copy preserves encoded pixel bytes; color format mapping; no D3D12 debug errors");
}
