#include <windows.h>
#include <d3d12.h>
#include <d3d12sdklayers.h>
#include <dxgi1_4.h>
#include <d3dcompiler.h>
#include <wrl/client.h>
#include <atomic>
#include <mutex>
#include <vector>
#include <cstdio>
#include <fstream>
#include <iterator>
static FILE* logFile=stdout;static uintptr_t backend{};
template<class T>T Read(uintptr_t p){T v{};SIZE_T n{};ReadProcessMemory(GetCurrentProcess(),reinterpret_cast<void*>(p),&v,sizeof(v),&n);return v;}
namespace TemporalPort {inline std::atomic<unsigned> renderEye{},epoch{};inline unsigned previousCounter{};}
#include "WaterHistory.h"
#include "ShadowPort.h"
template<class T>using Com=Microsoft::WRL::ComPtr<T>;
static void Check(HRESULT hr,unsigned line){if(FAILED(hr)){printf("HRESULT=%08lx line=%u\n",hr,line);ExitProcess(1);}}
#define H(hr) Check(hr,__LINE__)
int main(int argc,char**argv){if(argc!=7)return 2;Com<ID3D12Debug> debug;if(SUCCEEDED(D3D12GetDebugInterface(IID_PPV_ARGS(&debug))))debug->EnableDebugLayer();Com<IDXGIFactory4> factory;H(CreateDXGIFactory1(IID_PPV_ARGS(&factory)));Com<IDXGIAdapter> adapter;H(factory->EnumWarpAdapter(IID_PPV_ARGS(&adapter)));Com<ID3D12Device> device;H(D3D12CreateDevice(adapter.Get(),D3D_FEATURE_LEVEL_11_0,IID_PPV_ARGS(&device)));
 D3D12_ROOT_PARAMETER params[11]{};for(unsigned i=0;i<11;++i){params[i].ParameterType=D3D12_ROOT_PARAMETER_TYPE_32BIT_CONSTANTS;params[i].Constants={100+i,0,1};params[i].ShaderVisibility=D3D12_SHADER_VISIBILITY_ALL;}
 D3D12_DESCRIPTOR_RANGE ranges[2]={{D3D12_DESCRIPTOR_RANGE_TYPE_SRV,32,0,0,0},{D3D12_DESCRIPTOR_RANGE_TYPE_SAMPLER,2,0,0,0}};for(unsigned i=0;i<2;++i){params[i+3].ParameterType=D3D12_ROOT_PARAMETER_TYPE_DESCRIPTOR_TABLE;params[i+3].DescriptorTable={1,&ranges[i]};params[i+3].ShaderVisibility=D3D12_SHADER_VISIBILITY_PIXEL;}
 for(auto i:{1,2,6,10}){params[i].ParameterType=D3D12_ROOT_PARAMETER_TYPE_CBV;params[i].Descriptor={i==1?2u:i==2?3u:0u,0};params[i].ShaderVisibility=i<=2?D3D12_SHADER_VISIBILITY_ALL:i==6?D3D12_SHADER_VISIBILITY_PIXEL:D3D12_SHADER_VISIBILITY_VERTEX;}
 D3D12_ROOT_SIGNATURE_DESC rootDesc{11,params,0,nullptr,D3D12_ROOT_SIGNATURE_FLAG_ALLOW_INPUT_ASSEMBLER_INPUT_LAYOUT};Com<ID3DBlob> blob,error;H(D3D12SerializeRootSignature(&rootDesc,D3D_ROOT_SIGNATURE_VERSION_1,&blob,&error));Com<ID3D12RootSignature> root;H(device->CreateRootSignature(0,blob->GetBufferPointer(),blob->GetBufferSize(),IID_PPV_ARGS(&root)));
 const char* vs="struct O{float4 p:SV_POSITION;float4 a:TEXCOORD0;nointerpolation float4 b:TEXCOORD1;float4 c:TEXCOORD2;float4 d:TEXCOORD5;float4 e:TEXCOORD6;float4 f:TEXCOORD7;float4 g:TEXCOORD8;};O main(uint id:SV_VertexID){O o=(O)0;o.p=float4(id%2,id/2,0,1);return o;}";Com<ID3DBlob> vertex;H(D3DCompile(vs,strlen(vs),nullptr,nullptr,nullptr,"main","vs_5_0",0,0,&vertex,&error));
 D3D12_GRAPHICS_PIPELINE_STATE_DESC pd{};pd.pRootSignature=root.Get();pd.VS={vertex->GetBufferPointer(),vertex->GetBufferSize()};pd.SampleMask=~0u;pd.RasterizerState.FillMode=D3D12_FILL_MODE_SOLID;pd.RasterizerState.CullMode=D3D12_CULL_MODE_NONE;pd.RasterizerState.DepthClipEnable=TRUE;pd.DepthStencilState.DepthEnable=FALSE;pd.DepthStencilState.DepthFunc=D3D12_COMPARISON_FUNC_ALWAYS;pd.DepthStencilState.StencilEnable=FALSE;pd.PrimitiveTopologyType=D3D12_PRIMITIVE_TOPOLOGY_TYPE_TRIANGLE;pd.NumRenderTargets=3;pd.SampleDesc.Count=1;for(unsigned i=0;i<3;++i){pd.RTVFormats[i]=DXGI_FORMAT_R8G8B8A8_UNORM;pd.BlendState.RenderTarget[i].RenderTargetWriteMask=15;}
 ShadowPort::createOriginal=[](ID3D12Device*d,const D3D12_GRAPHICS_PIPELINE_STATE_DESC*p,REFIID i,void**o){return d->CreateGraphicsPipelineState(p,i,o);};Com<ID3D12PipelineState> original;uint64_t hash{};std::vector<unsigned char> firstCode;
 for(int i=1;i<argc;++i){std::ifstream f(argv[i],std::ios::binary);std::vector<unsigned char> code((std::istreambuf_iterator<char>(f)),{});pd.PS={code.data(),code.size()};Com<ID3D12PipelineState> p;auto result=ShadowPort::Create(device.Get(),&pd,IID_PPV_ARGS(&p));if(FAILED(result)){Com<ID3D12InfoQueue> info;if(SUCCEEDED(device.As(&info)))for(UINT64 m=0;m<info->GetNumStoredMessages();++m){SIZE_T n{};info->GetMessage(m,nullptr,&n);std::vector<char> b(n);auto message=reinterpret_cast<D3D12_MESSAGE*>(b.data());info->GetMessage(m,message,&n);puts(message->pDescription);}}H(result);if(i==1){firstCode=code;original=p;hash=ShaderHash(code.data(),unsigned(code.size()));}}
 if(ShadowPort::created!=6||ShadowPort::failed)return 3;
 ShadowPort::pipelines.clear();ShadowPort::created=0;pd.PS={firstCode.data(),firstCode.size()};
 static uintptr_t entry[2]{};entry[0]=reinterpret_cast<uintptr_t>(original.Get());
 ShadowPort::factoryOriginal=[](void* manager,const void* compute,const D3D12_GRAPHICS_PIPELINE_STATE_DESC* desc,const void* metadata,void* extra)->uintptr_t{if(manager!=reinterpret_cast<void*>(1)||compute||!desc||metadata!=reinterpret_cast<void*>(2)||extra!=reinterpret_cast<void*>(3))abort();return reinterpret_cast<uintptr_t>(entry);};
 for(unsigned i=0;i<2;++i)if(ShadowPort::Factory(reinterpret_cast<void*>(1),nullptr,&pd,reinterpret_cast<void*>(2),reinterpret_cast<void*>(3))!=reinterpret_cast<uintptr_t>(entry))return 11;
 if(ShadowPort::created!=1||ShadowPort::factoryTargets!=2)return 12;
 puts("PASS native cached-pipeline factory forwards all five arguments, preserves result and creates only one replacement on repeated cache hits");
 D3D12_COMMAND_QUEUE_DESC qd{};Com<ID3D12CommandQueue> queue;H(device->CreateCommandQueue(&qd,IID_PPV_ARGS(&queue)));Com<ID3D12CommandAllocator> allocator;H(device->CreateCommandAllocator(D3D12_COMMAND_LIST_TYPE_DIRECT,IID_PPV_ARGS(&allocator)));Com<ID3D12GraphicsCommandList> list;H(device->CreateCommandList(0,D3D12_COMMAND_LIST_TYPE_DIRECT,allocator.Get(),nullptr,IID_PPV_ARGS(&list)));list->SetGraphicsRootSignature(root.Get());list->SetPipelineState(original.Get());
 D3D12_RESOURCE_DESC d{};d.Dimension=D3D12_RESOURCE_DIMENSION_TEXTURE2D;d.Width=d.Height=4;d.MipLevels=d.DepthOrArraySize=1;d.Format=DXGI_FORMAT_R8G8B8A8_UNORM;d.SampleDesc.Count=1;d.Flags=D3D12_RESOURCE_FLAG_ALLOW_RENDER_TARGET;D3D12_HEAP_PROPERTIES hp{};hp.Type=D3D12_HEAP_TYPE_DEFAULT;Com<ID3D12Resource> depth;H(device->CreateCommittedResource(&hp,D3D12_HEAP_FLAG_NONE,&d,D3D12_RESOURCE_STATE_RENDER_TARGET,nullptr,IID_PPV_ARGS(&depth)));
 D3D12_DESCRIPTOR_HEAP_DESC hd{};hd.Type=D3D12_DESCRIPTOR_HEAP_TYPE_RTV;hd.NumDescriptors=1;Com<ID3D12DescriptorHeap> heap;H(device->CreateDescriptorHeap(&hd,IID_PPV_ARGS(&heap)));auto handle=heap->GetCPUDescriptorHandleForHeapStart();device->CreateRenderTargetView(depth.Get(),nullptr,handle);float red[]={1,0,0,1},green[]={0,1,0,1};list->ClearRenderTargetView(handle,red,0,nullptr);WaterHistory::Barrier(list.Get(),depth.Get(),0,D3D12_RESOURCE_STATE_RENDER_TARGET,D3D12_RESOURCE_STATE_PIXEL_SHADER_RESOURCE);
 d={};d.Dimension=D3D12_RESOURCE_DIMENSION_BUFFER;d.Width=4096;d.Height=1;d.MipLevels=d.DepthOrArraySize=1;d.SampleDesc.Count=1;d.Layout=D3D12_TEXTURE_LAYOUT_ROW_MAJOR;hp.Type=D3D12_HEAP_TYPE_UPLOAD;Com<ID3D12Resource> upload;H(device->CreateCommittedResource(&hp,D3D12_HEAP_FLAG_NONE,&d,D3D12_RESOURCE_STATE_GENERIC_READ,nullptr,IID_PPV_ARGS(&upload)));unsigned char* mapped{};H(upload->Map(0,nullptr,reinterpret_cast<void**>(&mapped)));memset(mapped,17,4096);memset(mapped+2048,238,528);
 std::vector<unsigned char> module(0x164b00);backend=reinterpret_cast<uintptr_t>(module.data());alignas(16) unsigned char holder[16]{},arena[96]{},allocation[128]{},state[0x3800]{},wrapper[128]{},depthAllocation[128]{};
 auto put=[](void* dst,uintptr_t v){memcpy(dst,&v,8);};put(module.data()+0x164a48,reinterpret_cast<uintptr_t>(holder));put(holder+8,reinterpret_cast<uintptr_t>(arena));put(arena,reinterpret_cast<uintptr_t>(allocation));put(arena+8,reinterpret_cast<uintptr_t>(mapped));put(allocation+0x30,reinterpret_cast<uintptr_t>(upload.Get()));put(allocation+0x40,upload->GetGPUVirtualAddress());put(state+0x3508,upload->GetGPUVirtualAddress());put(state+0x3510,upload->GetGPUVirtualAddress()+256);put(state+0x3538,upload->GetGPUVirtualAddress()+512);put(state+0x3550,upload->GetGPUVirtualAddress()+512);put(state+0x3540,upload->GetGPUVirtualAddress()+2048);put(state+0x3578,upload->GetGPUVirtualAddress());put(state+0xb48,reinterpret_cast<uintptr_t>(wrapper));put(wrapper,reinterpret_cast<uintptr_t>(depthAllocation));put(depthAllocation+0x30,reinterpret_cast<uintptr_t>(depth.Get()));unsigned pixel=D3D12_RESOURCE_STATE_PIXEL_SHADER_RESOURCE,one=1;memcpy(depthAllocation+0x48,&pixel,4);memcpy(depthAllocation+0x28,&one,4);
 ShadowPort::enabled=true;TemporalPort::renderEye=1;TemporalPort::epoch=1;TemporalPort::previousCounter=1;ShadowPort::Begin(queue.Get(),1,1,1);put(state+0x3550,0);{ShadowPort::Scope invalid(list.Get(),reinterpret_cast<uintptr_t>(state),hash,original.Get());}if(ShadowPort::captured!=0)return 13;put(state+0x3550,upload->GetGPUVirtualAddress()+512);{ShadowPort::Scope s(list.Get(),reinterpret_cast<uintptr_t>(state),hash,original.Get());}if(ShadowPort::captured!=1)return 4;
 WaterHistory::Barrier(list.Get(),depth.Get(),0,D3D12_RESOURCE_STATE_PIXEL_SHADER_RESOURCE,D3D12_RESOURCE_STATE_RENDER_TARGET);list->ClearRenderTargetView(handle,green,0,nullptr);WaterHistory::Barrier(list.Get(),depth.Get(),0,D3D12_RESOURCE_STATE_RENDER_TARGET,D3D12_RESOURCE_STATE_PIXEL_SHADER_RESOURCE);
 Com<ID3D12Resource> reads[2];hp.Type=D3D12_HEAP_TYPE_READBACK;for(auto& r:reads)H(device->CreateCommittedResource(&hp,D3D12_HEAP_FLAG_NONE,&d,D3D12_RESOURCE_STATE_COPY_DEST,nullptr,IID_PPV_ARGS(&r)));
 auto read=[&](unsigned i){WaterHistory::Barrier(list.Get(),depth.Get(),0,D3D12_RESOURCE_STATE_PIXEL_SHADER_RESOURCE,D3D12_RESOURCE_STATE_COPY_SOURCE);D3D12_TEXTURE_COPY_LOCATION dst{},src{};dst.pResource=reads[i].Get();dst.Type=D3D12_TEXTURE_COPY_TYPE_PLACED_FOOTPRINT;dst.PlacedFootprint.Footprint={DXGI_FORMAT_R8G8B8A8_UNORM,4,4,1,256};src.pResource=depth.Get();src.Type=D3D12_TEXTURE_COPY_TYPE_SUBRESOURCE_INDEX;list->CopyTextureRegion(&dst,0,0,0,&src,nullptr);WaterHistory::Barrier(list.Get(),depth.Get(),0,D3D12_RESOURCE_STATE_COPY_SOURCE,D3D12_RESOURCE_STATE_PIXEL_SHADER_RESOURCE);};
 TemporalPort::renderEye=2;{ShadowPort::Scope s(list.Get(),reinterpret_cast<uintptr_t>(state),hash,original.Get());read(0);}read(1);if(ShadowPort::applied!=1)return 5;
 auto& slot=ShadowPort::slots[ShadowPort::slotIndex];for(unsigned i=0;i<528;++i)if(slot.cpu[1024+i]!=17)return 6;for(unsigned i=0;i<64;++i)if(slot.cpu[1552+i]!=17)return 7;
 H(list->Close());ID3D12CommandList* lists[]={list.Get()};queue->ExecuteCommandLists(1,lists);ShadowPort::Present();H(ShadowPort::fence->SetEventOnCompletion(ShadowPort::serial,ShadowPort::event));if(WaitForSingleObject(ShadowPort::event,5000)!=WAIT_OBJECT_0)return 8;
 for(unsigned i=0;i<2;++i){unsigned char* bytes{};H(reads[i]->Map(0,nullptr,reinterpret_cast<void**>(&bytes)));for(unsigned y=0;y<4;++y)for(unsigned x=0;x<4;++x)if(bytes[y*256+x*4]!=(i?0:255)||bytes[y*256+x*4+1]!=(i?255:0))return 9;reads[i]->Unmap(0,nullptr);}
 Com<ID3D12InfoQueue> info;if(SUCCEEDED(device.As(&info)))for(UINT64 m=0;m<info->GetNumStoredMessages();++m){SIZE_T n{};info->GetMessage(m,nullptr,&n);std::vector<char> b(n);auto message=reinterpret_cast<D3D12_MESSAGE*>(b.data());info->GetMessage(m,message,&n);if(message->Severity<=D3D12_MESSAGE_SEVERITY_ERROR){puts(message->pDescription);return 10;}}
 ShadowPort::Report();puts("PASS all six DX12 replacement pipelines; left depth during right draw, native depth restored; b2 camera selected over poisoned b3, stale binding rejected; material preserved; fence completion");
}

